name: BeaconUtils
version: '${version}'
main: org.beaconstudios.beaconutils.BeaconUtils
api-version: '1.20'
commands:
  beaconutils:
    usage: /beaconutils
  entityfill:
    usage: /entityfill
  skin:
    usage: /skin
softdepend:
  - EnchantedBosses
  - SkillsLibrary2